global:

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

rule_files:
  - "node-exporter.rules"
  - "alertmanager.rules"
  - "prometheus.rules"
  - "blackbox.rules"

scrape_configs:
  - job_name: 'LinuxProdSec'
    scheme: https
    tls_config:
      ca_file: /etc/prometheus/ca.crt
      cert_file: /etc/prometheus/tls.crt
      key_file: /etc/prometheus/tls.key
    scrape_interval: 60s
    static_configs:
      - targets: ['yc-appsrv1.ycdisp.net:9100']
        labels:
          instance: 'yc-appsrv1'
          env: 'prod'
  - job_name: 'LinuxDevSec'
    scheme: https
    tls_config:
      ca_file: /etc/prometheus/ca.crt
      cert_file: /etc/prometheus/tls.crt
      key_file: /etc/prometheus/tls.key
    scrape_interval: 60s
    static_configs:
      - targets: ['yc-appsrv1-dev.local.lan:9100']
        labels:
          instance: 'yc-appsrv1-dev'
  - job_name: 'VMware'
    metrics_path: '/metrics'
    scrape_interval: 60s
    static_configs:
      - targets: ['vmware-exporter:9272']
        labels:
          instance: 'vcsa-1'
          env: 'prod'
  - job_name: 'Alertmanager'
    metrics_path: '/metrics'
    scrape_interval: 60s
    static_configs:
      - targets: ['alertmanager:9093']
        labels:
          instance: 'alertmanager'
  - job_name: 'WindowsDev'
    scrape_interval: 60s
    static_configs:
      - targets: ['HL-SRV1.homelab.local:9182']
        labels:
          instance: 'hl-srv1'
      - targets: ['HL-SQL1.homelab.local:9182']
        labels:
          instance: 'hl-sql1'
      - targets: ['HL-FSW.homelab.local:9182']
        labels:
          instance: 'hl-fsw'
      - targets: ['HL-CLUS16-1.homelab.local:9182']
        labels:
          instance: 'hl-clus16-1'
      - targets: ['HL-CLUS16-2.homelab.local:9182']
        labels:
          instance: 'hl-clus16-2'
      - targets: ['HL-CLUS16-R1.homelab.local:9182']
        labels:
          instance: 'hl-clus16-r1'
      - targets: ['HL-CLUS16-R2.homelab.local:9182']
        labels:
          instance: 'hl-clus16-r2'
  # - job_name: 'WindowsProd'
  #   scrape_interval: 60s
  #   static_configs:
  #     - targets: ['HL-DC1.homelab.local:9182']
  #       labels:
  #         instance: 'hl-dc1'
  #         env: 'prod'
  - job_name: 'LinuxDev'
    scrape_interval: 60s
    static_configs:
      - targets: ['podhost1.local.lan:9100']
        labels:
          instance: 'podhost1'
  - job_name: 'LinuxProd'
    scrape_interval: 60s
    static_configs:
      - targets: ['homenas.local.lan:9100']
        labels:
          instance: 'homenas'
          env: 'prod'
      - targets: ['homeassistant.local.lan:9100']
        labels:
          instance: 'homeassistant'
          env: 'prod'
  - job_name: 'UPS-Nut'
    metrics_path: /ups_metrics
    scrape_interval: 60s
    static_configs:
      - targets: ['dietpi1.local.lan:9199']
        labels:
          instance: 'nut_monitor'
          env: 'prod'
  - job_name: 'blackbox_http'
    metrics_path: /probe
    params:
      module: [http_2xx]  
    static_configs:
      - targets:
        - https://www.diversionforum.net 
        - https://www.ycdisp.com   
        labels:
          env: 'prod'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115  
  - job_name: 'blackbox_icmp'
    metrics_path: /probe
    params:
      module: [icmp]  
    static_configs:
      - targets:
        - 192.168.1.1
        - 192.168.1.4
        - 192.168.1.6
        - 192.168.1.7
        labels:
          env: 'prod'
      - targets:
        - 192.168.1.204
        labels:
          instance: 'esxinuc1'   
          env: 'prod'
      - targets:
        - 192.168.1.205
        labels:
          instance: 'esxinuc2'
          env: 'prod'
      - targets:
        - 192.168.1.206
        labels:
          instance: 'esxinuc3'
          env: 'prod'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115 
  - job_name: 'procurve1800-24g'
    static_configs:
      - targets:
        - 192.168.1.4  # SNMP device.
        labels:
          env: 'prod'
    metrics_path: /snmp
    params:
      auth: [public_v2]
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp:9116  # The SNMP exporter's real hostname:port.
  - job_name: 'unifi'
    static_configs:
      - targets:
        - 192.168.1.1
        - 192.168.1.6
        - 192.168.1.7
        labels:
          env: 'prod'
    metrics_path: /snmp
    params:
      auth: [public_v2]
      module: [ubiquiti_unifi]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp:9116  # The SNMP exporter's real hostname:port.=
  - job_name: 'snmp_exporter'
    static_configs:
      - targets: ['snmp:9116']
  - job_name: 'unifipoller'
    scrape_interval: 30s
    static_configs:
    - targets: ['localhost:9130']
  - job_name: 'unifipoller'
    scrape_interval: 30s
    static_configs:
    - targets: ['localhost:9130']