global:

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

rule_files:
  - "node-exporter.rules"
  - "alertmanager.rules"
  - "prometheus.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'LinuxProdSec'
    scheme: https
    tls_config:
      ca_file: /etc/prometheus/ca.crt
      cert_file: /etc/prometheus/tls.crt
      key_file: /etc/prometheus/tls.key
    scrape_interval: 60s
    static_configs:
      - targets: ['yc-appsrv1.ycdisp.net:9100']
        labels:
          instance: 'yc-appsrv1'
          env: 'prod'
  - job_name: 'LinuxDevSec'
    scheme: https
    tls_config:
      ca_file: /etc/prometheus/ca.crt
      cert_file: /etc/prometheus/tls.crt
      key_file: /etc/prometheus/tls.key
    scrape_interval: 60s
    static_configs:
      - targets: ['yc-appsrv1-dev.local.lan:9100']
        labels:
          instance: 'yc-appsrv1-dev'
  - job_name: 'VMware'
    metrics_path: '/metrics'
    scrape_interval: 60s
    static_configs:
      - targets: ['vmware-exporter:9272']
        labels:
          instance: 'vcsa-1'
          env: 'prod'
  - job_name: 'Alertmanager'
    metrics_path: '/metrics'
    scrape_interval: 60s
    static_configs:
      - targets: ['alertmanager:9093']
        labels:
          instance: 'alertmanager'
  - job_name: 'WindowsDev'
    scrape_interval: 60s
    static_configs:
      - targets: ['HL-SRV1.homelab.local:9182']
        labels:
          instance: 'hl-srv1'
      - targets: ['HL-SQL1.homelab.local:9182']
        labels:
          instance: 'hl-sql1'
      - targets: ['HL-FSW.homelab.local:9182']
        labels:
          instance: 'hl-fsw'
      - targets: ['HL-CLUS16-1.homelab.local:9182']
        labels:
          instance: 'hl-clus16-1'
      - targets: ['HL-CLUS16-2.homelab.local:9182']
        labels:
          instance: 'hl-clus16-2'
      - targets: ['HL-CLUS16-R1.homelab.local:9182']
        labels:
          instance: 'hl-clus16-r1'
      - targets: ['HL-CLUS16-R2.homelab.local:9182']
        labels:
          instance: 'hl-clus16-r2'
  - job_name: 'WindowsProd'
    scrape_interval: 60s
    static_configs:
      - targets: ['HL-DC1.homelab.local:9182']
        labels:
          instance: 'hl-dc1'
          env: 'prod'
  - job_name: 'LinuxDev'
    scrape_interval: 60s
    static_configs:
      - targets: ['podhost1.local.lan:9100']
        labels:
          instance: 'podhost1'
  - job_name: 'LinuxProd'
    scrape_interval: 60s
    static_configs:
      - targets: ['homenas.local.lan:9100']
        labels:
          instance: 'homenas'
          env: 'prod'
      - targets: ['homeassistant.local.lan:9100']
        labels:
          instance: 'homeassistant'
          env: 'prod'
  - job_name: 'UPS-Nut'
    metrics_path: /ups_metrics
    scrape_interval: 60s
    static_configs:
      - targets: ['dietpi1.local.lan:9199']
        labels:
          instance: 'nut_monitor'
          env: 'prod'
