{
 "title": "Climate",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Upstairs Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "timestart = uint(v: v.timeRangeStart)\ntimestop = uint(v: v.timeRangeStop)\nduration = duration(v:timestop - timestart)\n\nfrom(bucket: \"HA\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"°F\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.entity_id == \"upstairs_temperature\")\n  |> last()\n\n"
    }
   ]
  },
  {
   "title": "Master Bedroom Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "timestart = uint(v: v.timeRangeStart)\ntimestop = uint(v: v.timeRangeStop)\nduration = duration(v:timestop - timestart)\n\nfrom(bucket: \"HA\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"°F\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.entity_id == \"master_bedroom_temperature\")\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Office Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "timestart = uint(v: v.timeRangeStart)\ntimestop = uint(v: v.timeRangeStop)\nduration = duration(v:timestop - timestart)\n\nfrom(bucket: \"HA\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"°F\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.entity_id == \"office_temperature\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Charlize's Room Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "timestart = uint(v: v.timeRangeStart)\ntimestop = uint(v: v.timeRangeStop)\nduration = duration(v:timestop - timestart)\n\nfrom(bucket: \"HA\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"°F\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.entity_id == \"charlizes_room_temperature\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Bo's Room Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "timestart = uint(v: v.timeRangeStart)\ntimestop = uint(v: v.timeRangeStop)\nduration = duration(v:timestop - timestart)\n\nfrom(bucket: \"HA\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"°F\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.entity_id == \"bos_room_temperature\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Upstairs Humidity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "timestart = uint(v: v.timeRangeStart)\ntimestop = uint(v: v.timeRangeStop)\nduration = duration(v:timestop - timestart)\n\nfrom(bucket: \"HA\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"%\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.entity_id == \"upstairs_humidity\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "Main Floor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "%",
     "query": "timestart = uint(v: v.timeRangeStart)\ntimestop = uint(v: v.timeRangeStop)\nduration = duration(v:timestop - timestart)\n\nfrom(bucket: \"HA\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"%\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.entity_id == \"upstairs_humidity\" or r.entity_id == \"main_floor_humidity\" or r.entity_id == \"pirateweather_humidity\")\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "main_floor_humidity" }
     ]
    },
    {
     "alias": "Upstairs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "%",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "upstairs_humidity" }
     ]
    }
   ]
  },
  {
   "title": "Main Floor Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "timestart = uint(v: v.timeRangeStart)\ntimestop = uint(v: v.timeRangeStop)\nduration = duration(v:timestop - timestart)\n\nfrom(bucket: \"HA\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"°F\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.entity_id == \"main_floor_temperature\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Family Room Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "timestart = uint(v: v.timeRangeStart)\ntimestop = uint(v: v.timeRangeStop)\nduration = duration(v:timestop - timestart)\n\nfrom(bucket: \"HA\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"°F\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.entity_id == \"family_room_ecobee_sensor_temperature\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Living Room Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "timestart = uint(v: v.timeRangeStart)\ntimestop = uint(v: v.timeRangeStop)\nduration = duration(v:timestop - timestart)\n\nfrom(bucket: \"HA\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"°F\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.entity_id == \"living_room_ecobee_sensor_temperature\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Suite Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "timestart = uint(v: v.timeRangeStart)\ntimestop = uint(v: v.timeRangeStop)\nduration = duration(v:timestop - timestart)\n\nfrom(bucket: \"HA\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"°F\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.entity_id == \"suite_temperature\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Kitchen Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "timestart = uint(v: v.timeRangeStart)\ntimestop = uint(v: v.timeRangeStop)\nduration = duration(v:timestop - timestart)\n\nfrom(bucket: \"HA\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"°F\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.entity_id == \"kitchen_temperature\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Main Floor Humidity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "timestart = uint(v: v.timeRangeStart)\ntimestop = uint(v: v.timeRangeStop)\nduration = duration(v:timestop - timestart)\n\nfrom(bucket: \"HA\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"%\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.entity_id == \"main_floor_humidity\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Upstairs Temps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Bo's Room",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "°F",
     "query": "timestart = uint(v: v.timeRangeStart)\ntimestop = uint(v: v.timeRangeStop)\nduration = duration(v:timestop - timestart)\n\nfrom(bucket: \"HA\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"°F\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.entity_id == \"upstairs_temperature\" or r.entity_id == \"bos_room_temperature\" or r.entity_id == \"charlizes_room_temperature\" or r.entity_id == \"master_bedroom_temperature\" or r.entity_id == \"office_temperature\")\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "bos_room_temperature" }
     ]
    }
   ]
  },
  {
   "title": "Main Floor Temps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Suite",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "°F",
     "query": "timestart = uint(v: v.timeRangeStart)\ntimestop = uint(v: v.timeRangeStop)\nduration = duration(v:timestop - timestart)\n\nfrom(bucket: \"HA\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"°F\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.entity_id == \"main_floor_temperature\" or r.entity_id == \"main\" or r.entity_id == \"kitchen_temperature\" or r.entity_id == \"suite_temperature\" or r.entity_id == \"living_room_ecobee_sensor_temperature\")\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "suite_temperature" }
     ]
    }
   ]
  },
  {
   "title": "Upstairs HVAC Cooling/Heating Duration",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "timestart = uint(v: v.timeRangeStart)\ntimestop = uint(v: v.timeRangeStop)\nduration = duration(v:timestop - timestart)\n\nfrom(bucket: \"HA\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r.entity_id == \"upstairs_hvac_cooling\" or r.entity_id == \"upstairs_hvac_heating\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "Main Floor HVAC Cooling/Heating Duration",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "timestart = uint(v: v.timeRangeStart)\ntimestop = uint(v: v.timeRangeStop)\nduration = duration(v:timestop - timestart)\n\nfrom(bucket: \"HA\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r.entity_id == \"main_floor_hvac_cooling\" or r.entity_id == \"main_floor_hvac_heating\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")"
    }
   ]
  }
 ]
}