{
 "title": "Energy",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Solar Power Production (kW)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "timestart = uint(v: v.timeRangeStart)\ntimestop = uint(v: v.timeRangeStop)\nduration = duration(v:timestop - timestart)\n\nfrom(bucket: \"HA\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"W\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.entity_id == \"envoy_202233021811_current_power_production\")\n  |> map(fn: (r) => ({ r with _value: int(v: r._value) / 1000 }))\n  |> last()"
    }
   ]
  },
  {
   "title": "Home Power Consumption (kW)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "timestart = uint(v: v.timeRangeStart)\ntimestop = uint(v: v.timeRangeStop)\nduration = duration(v:timestop - timestart)\n\nfrom(bucket: \"HA\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"kW\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.entity_id == \"home_power_consumption\")\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Current Power Net/Debt (kW)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "timestart = uint(v: v.timeRangeStart)\ntimestop = uint(v: v.timeRangeStop)\nduration = duration(v:timestop - timestart)\n\nfrom(bucket: \"HA\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"kW\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.entity_id == \"rainforest_emu_2_power\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Monthly Energy Usage (kWh)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Monthly",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "kWh",
     "query": "timestart = uint(v: v.timeRangeStart)\ntimestop = uint(v: v.timeRangeStop)\nduration = duration(v:timestop - timestart)\n\nfrom(bucket: \"HA\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"kWh\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.entity_id == \"energy_monthly\")\n  |> last()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "energy_monthly" }
     ]
    }
   ]
  },
  {
   "title": "Max Home Power Consumption",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "timestart = uint(v: v.timeRangeStart)\ntimestop = uint(v: v.timeRangeStop)\nduration = duration(v:timestop - timestart)\n\nfrom(bucket: \"HA\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"kW\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.entity_id == \"home_power_consumption\")\n  |> max()"
    }
   ]
  },
  {
   "title": "Energy",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "alias": "Solar Production",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "W",
     "query": "timestart = uint(v: v.timeRangeStart)\ntimestop = uint(v: v.timeRangeStop)\nduration = duration(v:timestop - timestart)\n\nfrom(bucket: \"HA\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"W\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.entity_id == \"envoy_202233021811_current_power_production\")\n  |> map(fn: (r) => ({ r with _value: int(v: r._value) / 1000 }))\n  |> aggregateWindow(every: 10m, fn: mean, createEmpty: false)\n\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "entity_id",
       "operator": "=",
       "value": "envoy_202233021811_current_power_production"
      }
     ]
    },
    {
     "alias": "Home Power Consumption",
     "query": "timestart = uint(v: v.timeRangeStart)\ntimestop = uint(v: v.timeRangeStop)\nduration = duration(v:timestop - timestart)\n\nfrom(bucket: \"HA\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"kW\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.entity_id == \"home_power_consumption\")\n  |> aggregateWindow(every: 10m, fn: mean, createEmpty: false)\n"
    },
    {
     "alias": "Power Net/Debt",
     "query": "timestart = uint(v: v.timeRangeStart)\ntimestop = uint(v: v.timeRangeStop)\nduration = duration(v:timestop - timestart)\n\nfrom(bucket: \"HA\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"kW\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.entity_id == \"rainforest_emu_2_power\")\n  |> aggregateWindow(every: 10m, fn: mean, createEmpty: false)\n\n"
    }
   ]
  },
  {
   "title": "Inverters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "W",
     "query": "timestart = uint(v: v.timeRangeStart)\ntimestop = uint(v: v.timeRangeStop)\nduration = duration(v:timestop - timestart)\n\nfrom(bucket: \"HA\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"W\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.entity_id =~ /envoy_202233021811_inverter/)\n\n",
     "select": [
      [
       { "params": [ "friendly_name_str" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "entity_id",
       "operator": "=",
       "value": "envoy_202233021811_inverter_202227004654"
      }
     ]
    }
   ]
  },
  {
   "title": "Daily (kWh)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "alias": "Energy Consumption",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "query": "timestart = uint(v: v.timeRangeStart)\ntimestop = uint(v: v.timeRangeStop)\nduration = duration(v:timestop - timestart)\n\nfrom(bucket: \"HA\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"kWh\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.entity_id == \"energy_daily\")\n  |> aggregateWindow(every: 1d, fn: max, createEmpty: false)\n  |> fill(usePrevious: true)\n\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "energy_daily" }
     ]
    },
    {
     "alias": "Solar Production",
     "query": "timestart = uint(v: v.timeRangeStart)\ntimestop = uint(v: v.timeRangeStop)\nduration = duration(v:timestop - timestart)\n\nfrom(bucket: \"HA\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"Wh\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.entity_id == \"envoy_202233021811_today_s_energy_production\")\n  |> map(fn: (r) => ({ r with _value: int(v: r._value) / 1000 }))\n  |> aggregateWindow(every: 1d, fn: max, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Monthly (kWh)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "alias": "Energy Consumption",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "query": "timestart = uint(v: v.timeRangeStart)\ntimestop = uint(v: v.timeRangeStop)\nduration = duration(v:timestop - timestart)\n\nfrom(bucket: \"HA\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"kWh\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.entity_id == \"energy_monthly\")\n  |> aggregateWindow(every: 1mo, fn: max, createEmpty: false)\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "energy_daily" }
     ]
    },
    {
     "alias": "Solar Production",
     "query": "timestart = uint(v: v.timeRangeStart)\ntimestop = uint(v: v.timeRangeStop)\nduration = duration(v:timestop - timestart)\n\nfrom(bucket: \"HA\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"Wh\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.entity_id == \"envoy_202233021811_today_s_energy_production\")\n  |> map(fn: (r) => ({ r with _value: int(v: r._value) / 1000 }))\n  |> aggregateWindow(every: 1mo, fn: max, createEmpty: false)\n"
    }
   ]
  }
 ]
}